name: GitHub Action Demo
on: push
jobs:
  Second-Job:
    needs: Premier-Job
    name: Second Job
    runs-on: Ubuntu-latest
    steps:
      - run: echo "Second Job"
      - run: echo "Fin"
  Premier-Job:
    name: Premier Job
    runs-on: Ubuntu-latest
    steps:
      - run: echo "Premier Job"
      - run: echo "Fin"
